<?php

namespace Casaris\Bundle\BusinessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetRequestAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRequestAnswerRepository extends EntityRepository
{
}
