<?php

namespace Casaris\Bundle\BusinessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRequestRepository extends EntityRepository
{
}
