core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

business:
    resource: "@BusinessBundle/Controller/"
    type:     annotation
    prefix:   /bussiness

social:
    resource: "@SocialBundle/Controller/"
    type:     annotation
    prefix:   /

    
