<?php

namespace Casaris\Bundle\SocialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WeddingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingItemRepository extends EntityRepository
{
}
